apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: customers-service-policy
  namespace: petclinic
spec:
  selector:
    matchLabels:
      app: customers-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/petclinic/sa/api-gateway"]
    to:
    - operation:
        methods: ["GET", "POST"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: vets-service-policy
  namespace: petclinic
spec:
  selector:
    matchLabels:
      app: vets-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/petclinic/sa/api-gateway"]
    to:
    - operation:
        methods: ["GET"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: visits-service-policy
  namespace: petclinic
spec:
  selector:
    matchLabels:
      app: visits-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/petclinic/sa/api-gateway"]
    to:
    - operation:
        methods: ["GET", "POST"]
