apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      serviceAccountName: customers-service
      containers:
      - name: customers-service
        image: springcommunity/spring-petclinic-customers-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "native"
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "false"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://discovery-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: petclinic
spec:
  selector:
    app: customers-service
  ports:
  - port: 8081
    targetPort: 8081
